version: '3.8'

services:
  rag-forge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      # GOGC=50 is a good default for latency-sensitive APIs.
      # It triggers GC more often, reducing pause times.
      # Profile your app and adjust if needed:
      # - Increase to 80 or 100 if CPU is maxed out.
      # - Decrease to 30 if you have CPU to spare and want to minimize latency.
      - GOGC=50
      # Lower this to leave more memory for the browser processes, which are not
      # managed by the Go runtime's memory limiter.
      - GOMEMLIMIT=1000MiB
      # For CPU-bound browser tasks, this should be tuned to the number of available CPU threads.
      # For an 8-thread machine, where we assign 6 threads to this service, a value of 6 is ideal.
      - BROWSER_POOL_SIZE=6
    mem_limit: 2g
    env_file:
      - .env
    # Pin the Go service to the first 6 CPU threads (0-5).
    # This is a Linux-only feature and gives it dedicated resources.
    cpuset: "0-5"
    # Add this entire block for system-level network tuning
    sysctls:
      # Increase the number of incoming connections backlog.
      # Helps prevent connection drops during request spikes.
      - net.core.somaxconn=1024
      # Allow reuse of sockets in TIME_WAIT state for new connections.
      # Critical for high-concurrency servers to avoid ephemeral port exhaustion.
      - net.ipv4.tcp_tw_reuse=1
      # Increase the ephemeral port range.
      - net.ipv4.ip_local_port_range=1024 65535
      # Increase TCP read/write buffers.
      - net.core.rmem_max=16777216
      - net.core.wmem_max=16777216
      - net.ipv4.tcp_rmem=4096 87380 16777216
      - net.ipv4.tcp_wmem=4096 65536 16777216
    depends_on:
      - transcript-service
    command: ["./main"]

  transcript-service:
    build:
      context: ./transcript-service
      dockerfile: Dockerfile
    env_file:
      - .env
    # Pin the Python service to the remaining 2 CPU threads (6-7).
    # This prevents it from contending for CPU with the main Go application.
    # The service is internal, so we don't need to expose the port.
    cpuset: "6-7"

networks:
  default:
    driver: bridge