version: '3.8'

services:
  rag-forge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      - GOGC=50
    env_file:
      - .env
    depends_on:
      - transcript-service
    command: ["./main"]

  transcript-service:
    build:
      context: ./transcript-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

networks:
  default:
    driver: bridge